---
platform: linux

image_resource:
  type: docker-image
  source: {repository: composer/composer, tag: alpine}

inputs:
- name: resource-concourse-php

outputs:
- name: output-built-concourse-php

run:
  dir: resource-concourse-php
  path: resource-concourse-php/pipeline/build.sh
