---
platform: linux

image_resource:
  type: docker-image
  source: {repository: composer/composer, tag: alpine}

inputs:
- name: resource-concourse-php

outputs:
- name: built-concourse-php
  path: source

run:
  dir: resource-concourse-php
  path: pipeline/build.sh
